# Code generated by Renovate (or images/scripts/update-hubble-version.sh); DO NOT EDIT.

# renovate: datasource=github-releases depName=cilium/hubble
hubble_version="v0.10.0"

declare -A hubble_sha256
# renovate: datasource=github-releases depName=cilium/hubble digestVersion=v0.10.0
hubble_sha256[amd64]="b421b7cfb8a616d8206fcf725a21a0e168b47e7009a74f4070d7e7cced8ccfad"
# renovate: datasource=github-releases depName=cilium/hubble digestVersion=v0.10.0
hubble_sha256[arm64]="dd7dd0dab8c2234517a4f3b3ad1c65d1675f24dfafc6520b513fd088388a284c"
