# Code generated by images/scripts/update-hubble-version.sh; DO NOT EDIT.
declare -A hubble_sha256

# renovate: datasource=github-releases depName=cilium/hubble versioning=semver
hubble_version="v0.11.1"
hubble_sha256[amd64]="80dc54aaef4314de8ad64f5a95ae4d9067542defd69edd6a95574610a5c379bd"
hubble_sha256[arm64]="62fc0032202a3dd7de62839c2735aed0c9ee3f42699bdb47ef2dcd1f018099f5"
