// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetworkAttachmentRoutes Routes for this network attachment
//
// swagger:model NetworkAttachmentRoutes
type NetworkAttachmentRoutes struct {

	// Route destination
	Dst string `json:"dst,omitempty"`

	// Route gateway
	Gw string `json:"gw,omitempty"`
}

// Validate validates this network attachment routes
func (m *NetworkAttachmentRoutes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this network attachment routes based on context it is used
func (m *NetworkAttachmentRoutes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetworkAttachmentRoutes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetworkAttachmentRoutes) UnmarshalBinary(b []byte) error {
	var res NetworkAttachmentRoutes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
